### ISSUE TITLE
Crash when attempting to run the mod on a dedicated server.

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [tomdrever/Gadgets#1]
Minecraft version: 1.15.2
Gadgets version: 1.1
Curios version: 2.0.2.4
Forge version: 31.2.22

Whenever I attempt to run this mod on my multiplayer server, the server just crashes due to the mod failing to load, it runs on the client and in singleplayer just fine and with no issues, but just fails when I attempt to use it on a dedicated server. 

Crash Report:
[crash-2020-06-22_20.31.04-server.txt](https://github.com/tomdrever/Gadgets/files/4815871/crash-2020-06-22_20.31.04-server.txt)

**Comment by tomdrever** [comment]
Pushed a fix for this - Gadgets version 1.2 should be up on curseforge shortly.
