### ISSUE TITLE
[Enhancement] Rather than configuring Curios to add more slots, why not add crafting recipes to combine the gadgets?

### ISSUE THREAD

**Issue by Corvus20** [tomdrever/Gadgets#2]
Terraria's crafting tree for the PDA item takes all the informational accessories and combines them with each other, eventually resulting in the PDA (and by extension, the cell phone), with only takes up one slot rather than many slots,

**Comment by tomdrever** [comment]
Thanks for this suggestion! I agree the mod definitely needs something like this. The reason for using Curios slots is to let people customize what gadgets they use and what order they appear in and I want to keep that functionality, but so long as I have the time to update / work on the mod, I'll add something like the ability to combine gadgets eventually.

**Comment by tomdrever** [comment]
I've added a shapeless recipe for crafting any two Gadgets together to create a "Combined Gadget" (which can also be combined). I think this addresses the Curios slots so I'm going to close this issue, if there are any problems or related suggestions feel free to comment or open a new issue.
